### ISSUE TITLE
Manual Handoff Menu is not displayed

### ISSUE THREAD

**Issue by naerschhersch** [svengcz/TopSky-Tower#17]
The menu for manual handoff is grayed out and with one click the whole menu closes.
Tested on several airports.

**Comment by svengcz** [comment]
Are other stations online?
Was the pilot under your control, then was handed off to an other controller and returned to you?

**Comment by ascarion** [comment]
It seems to be generally not working. Whenever I try to handoff a pilot via the "Manual Handoff" menu entry in the menu bar, the menu just closes and nothing happens.

**Comment by naerschhersch** [comment]
Both yes. Tracked the plane, but could not handoff via manual transfer. (greyed out)

**Comment by svengcz** [comment]
Found potential reasons.
Code is refactored for version 0.18.1
