### ISSUE TITLE
Handoff Predicition in Leipzig is not working.

### ISSUE THREAD

**Issue by naerschhersch** [svengcz/TopSky-Tower#18]

**Comment by svengcz** [comment]
What does not work?
Is the prediction coming too late?

**Comment by naerschhersch** [comment]
The prediciton isnt showing up at all.

**Comment by svengcz** [comment]
Can you provide a logfile? I do not see an obvious bug

**Comment by naerschhersch** [comment]
nope sorry. Tried again, worked now.
Maybe some kind of weird random error.

**Comment by svengcz** [comment]
Which prediction direction is it?
Twr -> App/Ctr
Twr -> Gnd
Gnd -> Twr

**Comment by naerschhersch** [comment]
Twr -> App/Ctr

**Comment by svengcz** [comment]
Which app- or center-stations were online?
I do not see a bug in the sector hierarchies.
It can be possible, that a sector is missing.

**Comment by naerschhersch** [comment]
I'm not 100% sure, but that was EDWW_B_CTR.

**Comment by svengcz** [comment]
Does it mean that the aircraft left the own sector and no suggestion was given?
Or was it a wrong one?

**Comment by svengcz** [comment]
Tested it with a simulator session. Unable to reproduce the issue.
Handoffs where given to S_APP, EDMM_M_CTR, EDMM_G_CTR, EDWW_B_CTR.
Was it maybe an old sector file with a bug?

**Comment by naerschhersch** [comment]
Tested yesterday again, worked for me now. Maybe it was a temporary issue?

**Comment by svengcz** [comment]
Maybe, yes. I'll close the ticket.
