### ISSUE TITLE
Reset time if new Request set

### ISSUE THREAD

**Issue by tjarkbre** [svengcz/TopSky-Tower#25]
**Describe the bug**
When new/other request status is set, reset the time.

**Euroscope deteails:**
 - Version: 0.18.0
 - Other plugins: /

**Comment by svengcz** [comment]
The main idea was to keep the timer active.
The assumption was that a change of the request means, that the controller clicked wrong.

If the ground status changes accordingly, the timer is reset for the next request.
Can you validate this?

In which other cases do you want to reset the timer?

**Comment by tjarkbre** [comment]
"If the ground status changes accordingly, the timer is reset for the next request.
Can you validate this?"
Haven't checked that yet.

Would be useful to reset the timer, if the controller clicked wrong
