### ISSUE TITLE
Notams on multiple ASR

### ISSUE THREAD

**Issue by naerschhersch** [svengcz/TopSky-Tower#31]
**Describe the bug**
NOTAMS are only displayed in one ASR. Seems to be the first ASR opened in the instance.

**To Reproduce**
[EDDB.final.asr.txt](https://github.com/svengcz/TopSky-Tower/files/6485563/EDDB.final.asr.txt)
[EDDB.asr.txt](https://github.com/svengcz/TopSky-Tower/files/6485564/EDDB.asr.txt)

**Expected behavior**
NOTMAS (e.g. rwy clsd / stand clsd) should be displayed on every ASR-Instance.

**Screenshots**
*GND first loaded*
GND: https://prnt.sc/12yhkj3
TWR: https://prnt.sc/12yhl8g

*TWR first loaded*
GND: https://prnt.sc/12yhoju
TWR: https://prnt.sc/12yhnqh

**Euroscope details:**
 - Version: 3.2a(r29)

**Comment by naerschhersch** [comment]
seems to be the same for NTZ-Zones

**Comment by svengcz** [comment]
also solved with the current bugfix
