### ISSUE TITLE
Event Window bugged

### ISSUE THREAD

**Issue by lucianoasmus** [svengcz/TopSky-Tower#34]
**Describe the bug**
After opening up the event window it is stuck in the middle of the screen, does not show up and I am not able to close it.

**To Reproduce**
Will add logfile later.
Add ASR and configuration files. - Will do later.

**Expected behavior**
That the Event-routes window opens up and I could select todays event route.

**Screenshots**
https://prnt.sc/12ytgq5 (look at the middle of the screen)

**Euroscope deteails:**
 - Version: Beta32a29
 - Other plugins: ESCenterlines, ModeS, RG BRemen Plugin, AfvEuroScopeBridge

**Additional context**
I just tried to open the event window and it bugged.

**Comment by lucianoasmus** [comment]
@svengcz Do you still need a logfile and/or my ASR with config files?

**Comment by svengcz** [comment]
No, I could reproduce the error.
It will be fixed with the new version.
