### ISSUE TITLE
Euroscope crash

### ISSUE THREAD

**Issue by Phil061995** [svengcz/TopSky-Tower#38]
**Describe the bug**
Euroscope crashed without any further notice. Happend 4 times within an hour, 3 times shortly after assuming an outbound, 1 time randomly.

**To Reproduce**
Not able to provide any EuroScope - logfile of the issue.

Online as EDDF_C_GND, no station below, Tower above. Assumed aircraft via Topsky Callsign Menu.

**Euroscope details:**
 - ES Version: V3.2.1.29
 - Other plugins: CCAMS, Groundradar, Topsky, VCH
 - Plugin Version 0.18.1

**Comment by svengcz** [comment]
This is somehow a real weird bug.
It happens not very often.

Was it during a transfer-situation of the pilot to an other controller? 
Was it an inbound or outbound?

Do you know if the tag was somehow special?
Was it VFR or IFR?
No valid route or invalid runwaz/SID definition?

Did the system crash only after the pilot was tracked or did it crash as soon as the pilot was inside your sector?

**Comment by svengcz** [comment]
Please try the attached hotfix. Remove the .txt from the file ending. DLL is not supported by Github.
I found some candidates that can trigger the crash, but I am not sure.

Is it possible that you run a second euroscope in proxy mode that does not use the plugin?
It allows you to save the logfile after a crash of the other euroscope.
Sometimes are logfiles temporary saved here:
%APPDATA%\..\local\VirtualStore

[TopSky-Tower.dll.txt](https://github.com/svengcz/TopSky-Tower/files/6489601/TopSky-Tower.dll.txt)

**Comment by Phil061995** [comment]
It happened shortly after assuming the outbound. Some of these outbounds were inside a wrong tower area (sectofile bug). 
The GRP tags were used, TST items only used via lists. 
All flights were IFR. 
Route was correct but the flightplan was not worked on because of the sectorfile bug.
Only one ES was used.

**Comment by svengcz** [comment]
Was the aircraft moving that forced the crash?
Was it next to a holding point or was it on a runway?
If it was on a runway, was the runway active?

**Comment by svengcz** [comment]
Please add your configuration files to this ticket

**Comment by Phil061995** [comment]
It was at the gate. Default Settings from Berlin has been used with Airport file for Frankfurt by Tjark.
