### ISSUE TITLE
Problems with r29 Beta and Ground Status

### ISSUE THREAD

**Issue by tjarkbre** [svengcz/TopSky-Tower#4]
TT wont Sync every Ground Status with new beta of ES. STUP and Taxi In aren't synced

**Comment by svengcz** [comment]
Postponed, until the new beta is better tested

**Comment by svengcz** [comment]
Analyzed the problems between both versions.
It is not a bug between TopSky-Tower and the new Euroscope-version, it is an incompatibility between r26 and r29 of Euroscope.
The ground states changed and the old version cannot handle them correct.

The following pull-requests prepares TopSky-Tower to be compatible with both versions, but it does not make sencee to fix r26 and r29 compatibility issues.
