### ISSUE TITLE
Configuration error: TopSkyTowerSettingsLocal.txt:25: Unknown entry: AIRPORTS

### ISSUE THREAD

**Issue by lucianoasmus** [svengcz/TopSky-Tower#41]
**Describe the bug**
Error showing up while loading up. It doesn't affect the functionality of the Plugin.

**To Reproduce**
Add a EuroScope - logfile of the issue. - It is on system startup, nothing to do with a session.
~Describe which callsign triggers the issue.~
Add ASR and configuration files.
[TopSkyTowerSettings.txt](https://github.com/svengcz/TopSky-Tower/files/6489304/TopSkyTowerSettings.txt)
[TopSkyTowerSettingsLocal.txt](https://github.com/svengcz/TopSky-Tower/files/6489305/TopSkyTowerSettingsLocal.txt)

**Expected behavior**
No error to show up.

**Screenshots**
https://media.discordapp.net/attachments/709488770109669438/843479806317297664/unknown.png

**Euroscope deteails:**
 - Version: Beta32a29
 - Other plugins: ESCenterlines, ModeS, RG BRemen Plugin, AfvEuroScopeBridge

**Additional context**
As I said, for the normal user more of a cosmetic thing, because it does not affect any functionality. It is weird though, because my settings-local file does not have 25 lines and never had.

**Comment by svengcz** [comment]
Please attach your other TopSky-Tower configuration files.

**Comment by lucianoasmus** [comment]
[TopSkyTowerAirportEDDC.txt](https://github.com/svengcz/TopSky-Tower/files/6489934/TopSkyTowerAirportEDDC.txt)
[TopSkyTowerAirportEDDP.txt](https://github.com/svengcz/TopSky-Tower/files/6489935/TopSkyTowerAirportEDDP.txt)
[TopSkyTowerEventRoutes.txt](https://github.com/svengcz/TopSky-Tower/files/6489936/TopSkyTowerEventRoutes.txt)
[TopSkyTowerAircrafts.txt](https://github.com/svengcz/TopSky-Tower/files/6489937/TopSkyTowerAircrafts.txt)
[TopSkyTowerAirportEDDB.txt](https://github.com/svengcz/TopSky-Tower/files/6489938/TopSkyTowerAirportEDDB.txt)
