### ISSUE TITLE
Feature: Crossing Points

### ISSUE THREAD

**Issue by tjarkbre** [svengcz/TopSky-Tower#5]
The controller can give the pilot the clearance to cross the runway. The field then turns green and all other controllers know. Integration into the Safetynet.
Real function

**Comment by svengcz** [comment]
Do you have a video or picture how this should look like?
I cannot imagine how this should be implemented.

**Comment by svengcz** [comment]
Can you provide additional information?

**Comment by svengcz** [comment]
Closed due to missing feedback of creator
