### ISSUE TITLE
Handoff predictions

### ISSUE THREAD

**Issue by tjarkbre** [svengcz/TopSky-Tower#6]
In EDDF problems with prediction next controller. Only worked, after plane entered new sector.

**Comment by svengcz** [comment]
Please attach a logfile with the issue

**Comment by svengcz** [comment]
[EuroScope20210508.txt](https://github.com/svengcz/TopSky-Tower/files/6468719/EuroScope20210508.txt)
Logfile to reproduce the error

**Comment by svengcz** [comment]
This is a OBS-logfile, right?
How can you see that the handoffs do not work?

**Comment by svengcz** [comment]
Can you provide additional information?

**Comment by svengcz** [comment]
Closed due to missing information by issue creator
