### ISSUE TITLE
weird FL Error (FP-Checker)

### ISSUE THREAD

**Issue by naerschhersch** [svengcz/TopSky-Tower#62]
**Describe the bug**
weird FL Error shows up for no reason

**To Reproduce**
[EuroScope20210521.txt](https://github.com/svengcz/TopSky-Tower/files/6525041/EuroScope20210521.txt)
DLH578 shows weird error

**Screenshots**
https://prnt.sc/138isxj

**Euroscope deteails:**
 - Version: 3.2.1.29

**Comment by svengcz** [comment]
I reviewed your logfile and the pilot requested FL2800 and not FL280.
If I fix the requested FL to FL280, everything works fine.

Can you validate this?
