### ISSUE TITLE
Not working list/tag items

### ISSUE THREAD

**Issue by Phil061995** [svengcz/TopSky-Tower#75]
**Describe the bug**
Sometimes the "Flight Plan Check" works, sometimes it doesn't and shows just nothing. Login als TWR and DEL, with and without primary set.  Everything is set up correct (Settings, Airport File, etc.). No Topsky Tower functions/menus can be opened at that time, the usual ES menus are working as they should. TST Windows (e.g. Departure Sequenz) is displayed correct. TST is allowed to draw on everything. This bug was already there before Version 1.0. It does not depend on the list or tags used. Also occured for other users.

**To Reproduce**

**Expected behavior**

**Screenshots**
FPL List item is empty:
https://prnt.sc/1f6z9pr

**Euroscope deteails:**
 - Version: Latest Euroscope Version Beta 29
 - Other plugins: VCH, Topsky, GroundRadar Plugin, CCAMS

**Additional context**
Sectorfile and ESE are in the same folder as the euroscope.exe, all other files are at a different place.

**Comment by svengcz** [comment]
Can you add the content of the TopSky-Tower message window if you have these kind of issues?
I am not sure how to reproduce it or how to find the bug.

**Comment by svengcz** [comment]
After some chats could the issue be located in OnAsrContentLoaded.
