### ISSUE TITLE
Wrong primary radar projection when using rotated screen

### ISSUE THREAD

**Issue by Frenkii** [svengcz/TopSky-Tower#76]
**Describe the bug**
When using the screen rotate function in ES the projection of the primary radar simulation is wrong.

**Expected behavior**
The projection of the planes shall be correct even if you rotate the sceen.

**Screenshot**
![Screenshot](https://media.discordapp.net/attachments/802213496463949826/871333961513709568/unknown.png)

**Comment by svengcz** [comment]
But the aircrafts fit to the taxiways. Correct?
Are the aircrafts rotated in a wrong way if you rotate the screen?

**Comment by svengcz** [comment]
The targets are not rotated correct. The positions are valid every time
