### ISSUE TITLE
De-Activation of Radar Simulation

### ISSUE THREAD

**Issue by naerschhersch** [svengcz/TopSky-Tower#79]
**Is your feature request related to a problem? Please describe.**
I wish I could turn off the radar simulation so I wouldn't be forced to use it.
An adjustment over the brightness would also be useful.

**Describe the solution you'd like**
A new and simple settings menu for visual settings.

**Comment by svengcz** [comment]
You can disable the RADAR simulation via the settings configuration.
An brightness-change can be added.

**Comment by svengcz** [comment]
UI_SimulateRadar=0 disables the RADAR simulation
